module.exports = [
    {year:"2010", make:"Kia", model:"Sportage"},
    {year:"2010", make:"Kia", model:"Rio"},
    {year:"2010", make:"Kia", model:"Rondo"},
    {year:"2010", make:"Infiniti", model:"QX56"},
    {year:"2010", make:"Infiniti", model:"G"},
    {year:"2010", make:"Infiniti", model:"QX"},
    {year:"2010", make:"Chevrolet", model:"Aveo"},
    {year:"2010", make:"Chevrolet", model:"Traverse"},
    {year:"2010", make:"Chevrolet", model:"Equinox"},
    {year:"2010", make:"Chevrolet", model:"Silverado"},
    {year:"2010", make:"Chevrolet", model:"HHR"},
    {year:"2010", make:"Subaru", model:"Impreza WRX"},
    {year:"2010", make:"Subaru", model:"Outback"},
    {year:"2010", make:"Maybach", model:"57"},
    {year:"2010", make:"Maybach", model:"62"},
    {year:"2010", make:"Maybach", model:"Landaulet"},
    {year:"2010", make:"Cadillac", model:"CTS-V"},
    {year:"2010", make:"Cadillac", model:"CTS"},
    {year:"2010", make:"Lincoln", model:"Navigator L"},
    {year:"2010", make:"Ford", model:"Escape"},
    {year:"2010", make:"Ford", model:"Mustang"},
    {year:"2010", make:"Ford", model:"Focus"},
    {year:"2010", make:"Ford", model:"Explorer"},
    {year:"2010", make:"Ford", model:"Flex"},
    {year:"2010", make:"Ford", model:"Edge"},
    {year:"2010", make:"Ford", model:"F-Series"},
    {year:"2010", make:"Ford", model:"Fusion"},
    {year:"2010", make:"Ford", model:"Crown Victoria"},
    {year:"2010", make:"Ford", model:"Ranger"},
    {year:"2010", make:"Ford", model:"Taurus"},
    {year:"2010", make:"Ford", model:"Expedition"},
    {year:"2011", make:"Ford", model:"Flex"},
    {year:"2011", make:"Ford", model:"E150"},
    {year:"2011", make:"Ford", model:"E250"},
    {year:"2011", make:"Ford", model:"E350"},
    {year:"2011", make:"Ford", model:"Expedition EL"},
    {year:"2011", make:"Ford", model:"F150"},
    {year:"2011", make:"Ford", model:"F250"},
    {year:"2011", make:"Ford", model:"F350"},
    {year:"2011", make:"Ford", model:"F450"},
    {year:"2011", make:"Ford", model:"Crown Victoria"},
    {year:"2011", make:"Toyota", model:"Yaris"},
    {year:"2011", make:"Toyota", model:"4Runner"},
    {year:"2011", make:"Toyota", model:"Camry"},
    {year:"2011", make:"Toyota", model:"Sequoia"},
    {year:"2011", make:"Toyota", model:"Land Cruiser"},
    {year:"2011", make:"Toyota", model:"Avalon"},
    {year:"2011", make:"Toyota", model:"Matrix"},
    {year:"2011", make:"Toyota", model:"Tacoma"},
    {year:"2011", make:"Toyota", model:"Prius"},
    {year:"2011", make:"Toyota", model:"Highlander"},
    {year:"2011", make:"Toyota", model:"Tundra"},
    {year:"2011", make:"Toyota", model:"FJ Cruiser"},
    {year:"2011", make:"Toyota", model:"RAV4"},
    {year:"2011", make:"Toyota", model:"Corolla"},
    {year:"2011", make:"Toyota", model:"Sienna"},
    {year:"2011", make:"Toyota", model:"Venza"},
    {year:"2011", make:"Toyota", model:"Camry Hybrid"},
    {year:"2011", make:"Toyota", model:"TundraMax"},
    {year:"2011", make:"Mercedes-Benz", model:"GLK-Class"},
    {year:"2011", make:"Mercedes-Benz", model:"S-Class"},
    {year:"2011", make:"Mercedes-Benz", model:"CLS-Class"},
    {year:"2011", make:"Mercedes-Benz", model:"SLK-Class"},
    {year:"2011", make:"Mercedes-Benz", model:"E-Class"},
    {year:"2011", make:"Mercedes-Benz", model:"GL-Class"},
    {year:"2011", make:"Mercedes-Benz", model:"C-Class"},
    {year:"2011", make:"Mercedes-Benz", model:"G-Class"},
    {year:"2011", make:"Mercedes-Benz", model:"CL-Class"},
    {year:"2011", make:"Mercedes-Benz", model:"SLS AMG"},
    {year:"2011", make:"Audi", model:"S6"},
    {year:"2011", make:"Audi", model:"S5"},
    {year:"2011", make:"Audi", model:"Q5"},
    {year:"2011", make:"Audi", model:"A6"},
    {year:"2011", make:"Audi", model:"TT"},
    {year:"2011", make:"Honda", model:"Accord"},
    {year:"2011", make:"Honda", model:"Odyssey"},
    {year:"2011", make:"Honda", model:"Civic"},
    {year:"2011", make:"Honda", model:"Pilot"},
    {year:"2011", make:"Honda", model:"Element"},
    {year:"2011", make:"Honda", model:"Fit"},
    {year:"2011", make:"Honda", model:"CR-Z"},
    {year:"2011", make:"Honda", model:"Ridgeline"},
    {year:"2011", make:"Honda", model:"CR-V"},
    {year:"2011", make:"Honda", model:"Insight"},
    {year:"2011", make:"Honda", model:"Accord Crosstour"},
    {year:"2011", make:"Jeep", model:"Patriot"},
    {year:"2011", make:"Jeep", model:"Grand Cherokee"},
    {year:"2011", make:"Jeep", model:"Liberty"},
    {year:"2011", make:"Jeep", model:"Wrangler"},
    {year:"2011", make:"Jeep", model:"Compass"},
    {year:"2011", make:"BMW", model:"1 Series"},
    {year:"2011", make:"BMW", model:"3 Series"},
    {year:"2011", make:"BMW", model:"5 Series"},
    {year:"2011", make:"BMW", model:"7 Series"},
    {year:"2011", make:"BMW", model:"X6"},
    {year:"2011", make:"BMW", model:"M3"},
    {year:"2011", make:"BMW", model:"X3"},
    {year:"2011", make:"Lexus", model:"HS"},
    {year:"2011", make:"Lexus", model:"LX"},
    {year:"2011", make:"Lexus", model:"ES"},
    {year:"2011", make:"Lexus", model:"IS F"},
    {year:"2011", make:"Dodge", model:"Caravan"},
    {year:"2011", make:"Dodge", model:"Charger"},
    {year:"2011", make:"Dodge", model:"Grand Caravan"},
    {year:"2011", make:"Nissan", model:"Versa"},
    {year:"2011", make:"Nissan", model:"JUKE"},
    {year:"2011", make:"Nissan", model:"Murano"},
    {year:"2011", make:"Chevrolet", model:"Silverado"},
    {year:"2011", make:"Chevrolet", model:"Traverse"},
    {year:"2011", make:"Chevrolet", model:"Colorado"},
    {year:"2011", make:"Chevrolet", model:"Avalanche"},
    {year:"2011", make:"Chevrolet", model:"Impala"},
    {year:"2011", make:"Porsche", model:"911"},
    {year:"2011", make:"Porsche", model:"Cayenne"},
    {year:"2011", make:"Porsche", model:"Panamera"},
    {year:"2011", make:"Porsche", model:"Boxster"},
    {year:"2011", make:"Porsche", model:"Cayman"},
    {year:"2011", make:"Tesla", model:"Roadster"},
    {year:"2011", make:"Ram", model:"1500"},
    {year:"2011", make:"Ram", model:"2500"},
    {year:"2011", make:"Ram", model:"3500"},
    {year:"2011", make:"Ram", model:"Dakota"},
    {year:"2012", make:"Porsche", model:"911"},
    {year:"2012", make:"Porsche", model:"Cayenne"},
    {year:"2012", make:"Porsche", model:"Panamera"},
    {year:"2012", make:"Porsche", model:"Boxster"},
    {year:"2012", make:"Porsche", model:"Cayman"},
    {year:"2012", make:"Nissan", model:"Altima"},
    {year:"2012", make:"Nissan", model:"370Z"},
    {year:"2012", make:"Nissan", model:"Murano"},
    {year:"2012", make:"Nissan", model:"Armada"},
    {year:"2012", make:"Nissan", model:"Pathfinder"},
    {year:"2012", make:"Nissan", model:"Leaf"},
    {year:"2012", make:"Nissan", model:"Xterra"},
    {year:"2012", make:"Cadillac", model:"SRX"},
    {year:"2012", make:"Cadillac", model:"Escalade ESV"},
    {year:"2012", make:"Cadillac", model:"Escalade EXT"},
    {year:"2012", make:"Audi", model:"TT"},
    {year:"2012", make:"Audi", model:"A7"},
    {year:"2012", make:"Audi", model:"S5"},
    {year:"2012", make:"Audi", model:"A4"},
    {year:"2012", make:"Audi", model:"Q7"},
    {year:"2012", make:"Audi", model:"S4"},
    {year:"2012", make:"Volkswagen", model:"New Beetle"},
    {year:"2012", make:"Volkswagen", model:"Passat"},
    {year:"2012", make:"Volkswagen", model:"Tiguan"},
    {year:"2012", make:"Volkswagen", model:"GTI"},
    {year:"2012", make:"Volkswagen", model:"CC"},
    {year:"2012", make:"Land Rover", model:"Range Rover"},
    {year:"2012", make:"Land Rover", model:"Discovery"},
    {year:"2012", make:"Land Rover", model:"Range Rover Sport"},
    {year:"2012", make:"Land Rover", model:"Range Rover Evoque"},
    {year:"2012", make:"Land Rover", model:"LR2"},
    {year:"2012", make:"Land Rover", model:"LR4"},
    {year:"2012", make:"Honda", model:"Odyssey"},
    {year:"2012", make:"Honda", model:"Accord"},
    {year:"2012", make:"Honda", model:"Civic"},
    {year:"2012", make:"Honda", model:"Ridgeline"},
    {year:"2012", make:"Honda", model:"Fit"},
    {year:"2012", make:"Honda", model:"Insight"},
    {year:"2012", make:"Honda", model:"CR-Z"},
    {year:"2012", make:"Honda", model:"Pilot"},
    {year:"2012", make:"Honda", model:"FCX Clarity"},
    {year:"2012", make:"Honda", model:"Crosstour"},
    {year:"2012", make:"Honda", model:"CR-V"},
    {year:"2012", make:"Hyundai", model:"Elantra"},
    {year:"2012", make:"Hyundai", model:"Veracruz"},
    {year:"2012", make:"Hyundai", model:"Sonata"},
    {year:"2012", make:"Hyundai", model:"Tucson"},
    {year:"2012", make:"Hyundai", model:"Veloster"},
    {year:"2012", make:"Hyundai", model:"Azera"},
    {year:"2012", make:"Ford", model:"Focus"},
    {year:"2012", make:"Ford", model:"Mustang"},
    {year:"2012", make:"Ford", model:"Escape"},
    {year:"2012", make:"Ford", model:"Fusion"},
    {year:"2012", make:"Ford", model:"Taurus"},
    {year:"2012", make:"Ford", model:"Fiesta"},
    {year:"2012", make:"Ford", model:"Explorer"},
    {year:"2012", make:"Ford", model:"Expedition"},
    {year:"2012", make:"Ford", model:"Edge"},
    {year:"2012", make:"Saab", model:"9-3"},
    {year:"2012", make:"Chevrolet", model:"Equinox"},
    {year:"2012", make:"Chevrolet", model:"Impala"},
    {year:"2012", make:"Chevrolet", model:"Avalanche"},
    {year:"2012", make:"Chevrolet", model:"Express 1500"},
    {year:"2012", make:"Chevrolet", model:"Express 2500"},
    {year:"2012", make:"BMW", model:"1 Series"},
    {year:"2012", make:"BMW", model:"3 Series"},
    {year:"2012", make:"BMW", model:"5 Series"},
    {year:"2012", make:"BMW", model:"6 Series"},
    {year:"2012", make:"BMW", model:"7 Series"},
    {year:"2012", make:"BMW", model:"M3"},
    {year:"2012", make:"BMW", model:"X3"},
    {year:"2012", make:"BMW", model:"X5"},
    {year:"2012", make:"BMW", model:"X5 M"},
    {year:"2012", make:"BMW", model:"X6"},
    {year:"2012", make:"BMW", model:"X6 M"},
    {year:"2012", make:"BMW", model:"Z4"},
    {year:"2012", make:"Toyota", model:"Sienna"},
    {year:"2012", make:"Toyota", model:"Camry"},
    {year:"2012", make:"Toyota", model:"Avalon"},
    {year:"2012", make:"Toyota", model:"Corolla"},
    {year:"2012", make:"Toyota", model:"Matrix"},
    {year:"2012", make:"Toyota", model:"Prius"},
    {year:"2012", make:"Toyota", model:"Tacoma"},
    {year:"2012", make:"Toyota", model:"Tundra"},
    {year:"2012", make:"Toyota", model:"Venza"},
    {year:"2012", make:"Acura", model:"ZDX"},
    {year:"2012", make:"Acura", model:"MDX"},
    {year:"2012", make:"Acura", model:"TSX"},
    {year:"2012", make:"Acura", model:"TL"},
    {year:"2012", make:"Acura", model:"RL"},
    {year:"2012", make:"Acura", model:"RDX"},
    {year:"2012", make:"Mercedes-Benz", model:"SL-Class"},
    {year:"2012", make:"Mercedes-Benz", model:"M-Class"},
    {year:"2012", make:"Mercedes-Benz", model:"R-Class"},
    {year:"2012", make:"Mercedes-Benz", model:"SLK-Class"},
    {year:"2012", make:"Mercedes-Benz", model:"SLS-Class"},
    {year:"2012", make:"Lexus", model:"RX"},
    {year:"2012", make:"Lexus", model:"LS"},
    {year:"2012", make:"Lexus", model:"IS"},
    {year:"2012", make:"Lexus", model:"IS-F"},
    {year:"2012", make:"Lexus", model:"CT"},
    {year:"2012", make:"Lexus", model:"RX Hybrid"},
    {year:"2012", make:"Lexus", model:"LS Hybrid"},
    {year:"2012", make:"Dodge", model:"Avenger"},
    {year:"2012", make:"Dodge", model:"Caravan"},
    {year:"2012", make:"Dodge", model:"Charger"},
    {year:"2012", make:"Dodge", model:"Challenger"},
    {year:"2012", make:"Tesla", model:"model S"},
    {year:"2012", make:"Tesla", model:"Roadster"},
    {year:"2013", make:"Ford", model:"Fiesta"},
    {year:"2013", make:"Ford", model:"Flex"},
    {year:"2013", make:"Ford", model:"Focus"},
    {year:"2013", make:"Ford", model:"Focus ST"},
    {year:"2013", make:"Ford", model:"Fusion"},
    {year:"2013", make:"Ford", model:"Mustang"},
    {year:"2013", make:"Ford", model:"Transit Connect"},
    {year:"2013", make:"Hyundai", model:"Veloster"},
    {year:"2013", make:"Hyundai", model:"Accent"},
    {year:"2013", make:"Hyundai", model:"Elantra"},
    {year:"2013", make:"Hyundai", model:"Equus"},
    {year:"2013", make:"Hyundai", model:"Genesis Coupe"},
    {year:"2013", make:"Hyundai", model:"Sonata"},
    {year:"2013", make:"Chevrolet", model:"Cruze"},
    {year:"2013", make:"Chevrolet", model:"Malibu"},
    {year:"2013", make:"Chevrolet", model:"Tahoe"},
    {year:"2013", make:"Audi", model:"S4"},
    {year:"2013", make:"BMW", model:"X5"},
    {year:"2013", make:"BMW", model:"X5 M"},
    {year:"2013", make:"BMW", model:"X6"},
    {year:"2013", make:"BMW", model:"X6 M"},
    {year:"2013", make:"Infiniti", model:"JX"},
    {year:"2013", make:"Jaguar", model:"XK Series"},
    {year:"2013", make:"Kia", model:"Rio"},
    {year:"2013", make:"Kia", model:"Sorento"},
    {year:"2013", make:"Lexus", model:"GS"},
    {year:"2013", make:"Lexus", model:"LX"},
    {year:"2013", make:"Lexus", model:"RX"},
    {year:"2013", make:"Mazda", model:"CX-5"},
    {year:"2013", make:"Mazda", model:"MAZDA6"},
    {year:"2013", make:"Nissan", model:"Altima"},
    {year:"2013", make:"Nissan", model:"GT-R"},
    {year:"2013", make:"Rolls-Royce", model:"Phantom"},
    {year:"2013", make:"Subaru", model:"BRZ"},
    {year:"2013", make:"Toyota", model:"Land Cruiser"},
    {year:"2013", make:"Toyota", model:"Venza"}]